import {Outfit} from "next/font/google";
import "./globals.css";
import BottomNavbar from "../../component/BottomNavbar";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "MakanGEH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${outfit.variable}h-full antialiased`}
    >
      <body>
        {children}
        <BottomNavbar/>
      </body>
    </html>
  );
}
