import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../component/Header";
import Navbar2 from "../../component/navbar2";
const data = await fetch("https://porto-backend-silk.vercel.app/menu")
const posts = await data.json()
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MakanGEH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body >
        {children}
        <Navbar2/>
      </body>
    </html>
  );
}
